### ISSUE TITLE
Description typo

### ISSUE THREAD

**Issue by eegeeZA** [mattleblanc/chrome-spoopy#1]
Just a heads up on the small typos (2) in your repository description.

**Comment by Moredread** [comment]
I think that's a case of "I see what you did there"

**Comment by eegeeZA** [comment]
Well, just saying.. think you had your own extension enabled when you edited your description.

i.e. `<span itemprop="about">...</span>` on https://github.com/mattleblanc/chrome-spoopy

**Comment by mattleblanc** [comment]
That was the joke. ;)
